In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("Amazon_Ecommerce.csv")

print(df.shape)
df.head()

(1000000, 20)

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43,71,S2679,4.3,2025-03-04,6,Bangalore,Tablet,UPI,True,Returned
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13,119,S9279,4.9,2025-12-12,1,Delhi,Tablet,UPI,True,Returned
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46,229,S5557,4.9,2024-04-25,1,Chennai,Mobile App,Credit Card,True,Returned
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6,52,S2519,3.1,2025-12-18,2,Mumbai,Web,UPI,False,In Transit
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48,274,S3045,2.6,2024-05-16,5,Delhi,Web,UPI,False,Delayed

In [ ]:
#Data type checking
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 20 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   user_id             1000000 non-null  object
 1   product_id          1000000 non-null  object
 2   category            1000000 non-null  object
 3   subcategory         1000000 non-null  object
 4   brand               1000000 non-null  object
 5   price               1000000 non-null  float64
 6   discount            1000000 non-null  float64
 7   final_price         1000000 non-null  float64
 8   rating              1000000 non-null  float64
 9   review_count        1000000 non-null  int64
 10  stock               1000000 non-null  int64
 11  seller_id           1000000 non-null  object
 12  seller_rating       1000000 non-null  float64
 13  purchase_date       1000000 non-null  object
 14  shipping_time_days  1000000 non-null  int64
 15  location            1000000 non-null  object
 16  device              1000000 non-null  object
 17  payment_method      1000000 non-null  object
 18  is_returned         1000000 non-null  bool
 19  delivery_status     1000000 non-null  object
dtypes: bool(1), float64(5), int64(3), object(11)
memory usage: 145.9+ MB

In [ ]:
df['purchase_date'] = pd.to_datetime(df['purchase_date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 20 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   user_id             1000000 non-null  object
 1   product_id          1000000 non-null  object
 2   category            1000000 non-null  object
 3   subcategory         1000000 non-null  object
 4   brand               1000000 non-null  object
 5   price               1000000 non-null  float64
 6   discount            1000000 non-null  float64
 7   final_price         1000000 non-null  float64
 8   rating              1000000 non-null  float64
 9   review_count        1000000 non-null  int64
 10  stock               1000000 non-null  int64
 11  seller_id           1000000 non-null  object
 12  seller_rating       1000000 non-null  float64
 13  purchase_date       1000000 non-null  datetime64[ns]
 14  shipping_time_days  1000000 non-null  int64
 15  location            1000000 non-null  object
 16  device              1000000 non-null  object
 17  payment_method      1000000 non-null  object
 18  is_returned         1000000 non-null  bool
 19  delivery_status     1000000 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(5), int64(3), object(10)
memory usage: 145.9+ MB

In [ ]:
# Missing values checking
df.isnull().sum()

user_id               0
product_id            0
category              0
subcategory           0
brand                 0
price                 0
discount              0
final_price           0
rating                0
review_count          0
stock                 0
seller_id             0
seller_rating         0
purchase_date         0
shipping_time_days    0
location              0
device                0
payment_method        0
is_returned           0
delivery_status       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#Duplicate IDs Checking
print(df['user_id'].nunique())
print(df['product_id'].nunique())
print(df['seller_id'].nunique())

603815
89999
9000

In [ ]:
#Validate Numerical Data

df[['price', 'final_price']].describe()

                price     final_price
count  1000000.000000  1000000.000000
mean     13224.119093     9938.876985
std      18079.626921    14271.885557
min        200.030000      101.460000
25%       2700.147500     1705.930000
50%       4971.830000     3790.795000
75%      14134.482500    10384.440000
max      79999.700000    75831.110000

In [ ]:
(df['price'] <= 0).sum()
(df['final_price'] <= 0).sum()

np.int64(0)

In [ ]:
#Statistical summary
df.describe()

,price,discount,final_price,rating,review_count,stock,seller_rating,purchase_date,shipping_time_days
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000,1000000.000000
mean,13224.119093,28.996161,9938.876985,3.927226,32.626704,250.023345,3.750030,2025-03-30 23:32:00.384000256,3.166389
min,200.030000,5.000000,101.460000,1.500000,0.000000,0.000000,2.500000,2024-03-31 00:00:00,1.000000
25%,2700.147500,16.910000,1705.930000,3.600000,10.000000,125.000000,3.100000,2024-09-29 00:00:00,2.000000
50%,4971.830000,28.070000,3790.795000,3.900000,20.000000,250.000000,3.800000,2025-03-31 00:00:00,3.000000
75%,14134.482500,39.240000,10384.440000,4.300000,39.000000,375.000000,4.400000,2025-09-30 00:00:00,5.000000
max,79999.700000,70.000000,75831.110000,5.000000,3408.000000,500.000000,5.000000,2026-03-31 00:00:00,6.000000
std,18079.626921,14.681077,14271.885557,0.519443,43.382201,144.567038,0.722092,NaN,1.674178

In [ ]:
#Shipping time
df['shipping_time_days'].value_counts().sort_index()

shipping_time_days
1    232944
2    167372
3    166095
4    167347
5    166424
6     99818
Name: count, dtype: int64

In [ ]:
#Categorical Consistency Checking
for col in ['category', 'subcategory', 'brand',
            'location', 'device', 'payment_method',
            'delivery_status']:
    print("\n", col)
    print(df[col].unique())

 category
['Electronics' 'Sports' 'Beauty' 'Home' 'Clothing']

 subcategory
['Mobile' 'Outdoor' 'Fitness' 'Makeup' 'Decor' 'Furniture' 'Kids' 'Women'
 'Cycling' 'Laptop' 'Skincare' 'Men' 'Camera' 'Kitchen' 'Haircare'
 'Headphones']

 brand
['H&M' 'Samsung' 'Sony' 'HP' 'Adidas' 'Apple' 'Nike' 'Boat' 'Zara' 'LG'
 'Lenovo' 'Puma']

 location
['Bangalore' 'Delhi' 'Chennai' 'Mumbai' 'Hyderabad']

 device
['Tablet' 'Mobile App' 'Web']

 payment_method
['UPI' 'Credit Card' 'Debit Card' 'Cash on Delivery']

 delivery_status
['Returned' 'In Transit' 'Delayed' 'Delivered']

In [ ]:
#Delivery Status vs Return Status
pd.crosstab(
    df['is_returned'],
    df['delivery_status']
)

delivery_status  Delayed  Delivered  In Transit  Returned
is_returned
False             294983     295234      293793         0
True                   0          0           0    115990

In [ ]:
#Category analysis
df.groupby('category')['final_price'].sum().sort_values(ascending=False)

category
Electronics    6.579048e+09
Home           1.529978e+09
Sports         1.124849e+09
Beauty         3.759517e+08
Clothing       3.290504e+08
Name: final_price, dtype: float64

In [ ]:
df['category'].value_counts()

category
Home           200922
Electronics    200038
Sports         199889
Clothing       199824
Beauty         199327
Name: count, dtype: int64

In [ ]:
#Customer analysis
customer_sales = (
    df.groupby('user_id')['final_price']
      .sum()
      .sort_values(ascending=False)
)

customer_sales.head(10)

user_id
U434268    229853.10
U902761    207234.79
U454661    199875.10
U384705    195983.73
U706383    195247.80
U978563    192137.94
U746513    188840.50
U224240    186945.13
U471344    181008.08
U877443    180892.29
Name: final_price, dtype: float64

In [ ]:
#Seller analysis
seller_sales = (
    df.groupby('seller_id')['final_price']
      .sum()
      .sort_values(ascending=False)
)

seller_sales.head(10)

seller_id
S7740    1891954.53
S2013    1810498.08
S4656    1791917.86
S6442    1786697.11
S2478    1776687.77
S6505    1765031.94
S9944    1757840.15
S4105    1749599.85
S3684    1746322.26
S5719    1744748.24
Name: final_price, dtype: float64

In [ ]:
#Time-based analysis
monthly_revenue = (
    df.groupby(df['purchase_date'].dt.to_period('M'))['final_price']
      .sum()
)

monthly_revenue

purchase_date
2024-03    1.388802e+07
2024-04    4.096292e+08
2024-05    4.207856e+08
2024-06    4.051715e+08
2024-07    4.217882e+08
2024-08    4.202220e+08
2024-09    4.039997e+08
2024-10    4.235672e+08
2024-11    4.118936e+08
2024-12    4.220663e+08
2025-01    4.247258e+08
2025-02    3.787897e+08
2025-03    4.230896e+08
2025-04    4.033051e+08
2025-05    4.200312e+08
2025-06    4.056538e+08
2025-07    4.213890e+08
2025-08    4.265546e+08
2025-09    3.999008e+08
2025-10    4.222367e+08
2025-11    4.056734e+08
2025-12    4.281423e+08
2026-01    4.214767e+08
2026-02    3.812453e+08
2026-03    4.236515e+08
Freq: M, Name: final_price, dtype: float64

In [ ]:
df.shape

(1000000, 20)

In [ ]:
df.to_csv('Amazon_Ecommerce_Cleaned.csv', index=False)

In [ ]:
from google.colab import files
files.download('Amazon_Ecommerce_Cleaned.csv')